# core/interfaces.py (file baru)
from __future__ import annotations
from typing import Optional, Protocol
from core.state_models import UserState, WorldState

class UserStateStore(Protocol):
    def load_user_state(self, user_id: str) -> Optional[UserState]: ...
    def save_user_state(self, state: UserState) -> None: ...

class WorldStateStore(Protocol):
    def load_world_state(self) -> Optional[WorldState]: ...
    def save_world_state(self, state: WorldState) -> None: ...
